-- ============================================================
-- 需求：{{requirement_name}}
-- 目标表：{{target_table}}
-- 源表：{{source_tables}}
-- 作者：aqueduct
-- 日期：{{date}}
-- 描述：{{description}}
-- ============================================================

-- ============================================================
-- 示例 1：简单场景（≤3 张源表）— 子查询方式
-- ============================================================
-- insert overwrite table dw_demo.dws_emp_tool_daily_di partition (inc_day = '${bizdate}')
-- select
--     a.emp_code,
--     a.emp_name,
--     coalesce(b.dept_name,'') as dept_name,
--     coalesce(a.tool_total_num,0) as tool_total_num
-- from (
--     select
--         emp_code,
--         emp_name,
--         tool_total_num
--     from dwd.emp_info_di
--     where inc_day = '${bizdate}'
--         and employ_status = '在职'
-- ) a
-- left join (
--     select
--         emp_code,
--         dept_name
--     from dwd.dim_dept_info_df
--     where inc_day = '${bizdate}'
-- ) b
-- on a.emp_code = b.emp_code
-- ;

-- ============================================================
-- 示例 2：复杂场景（4-6 张源表）— CTE 方式
-- ============================================================
-- CTE 优势：逻辑从上到下读，比嵌套括号清晰
-- CTE 局限：中间结果不落地，数据问题排查时需手动拆出 CTE 单独跑
-- with emp_base as (
--     select
--         emp_code,
--         emp_name,
--         dept_code,
--         area_code,
--         employ_status
--     from dwd.emp_info_di
--     where inc_day = '${bizdate}'
--         and employ_status = '在职'
--         and position_attr_tx = '一线'
-- ),
-- tool_agg as (
--     select
--         emp_code,
--         count(tool_name) as tool_cnt,
--         coalesce(sum(tool_total_num),0) as tool_total
--     from dwd.emp_tool_di
--     where inc_day = '${bizdate}'
--     group by emp_code
-- ),
-- order_agg as (
--     select
--         emp_code,
--         count(order_id) as order_cnt,
--         coalesce(sum(pay_amount),0) as gmv
--     from dwd.dwd_order_detail_di
--     where inc_day = '${bizdate}'
--         and order_status >= '20'
--     group by emp_code
-- )
-- insert overwrite table dw_demo.dws_emp_daily_di partition (inc_day = '${bizdate}')
-- select
--     e.emp_code,
--     e.emp_name,
--     coalesce(t.tool_cnt,0) as tool_cnt,
--     t.tool_total,
--     coalesce(o.order_cnt,0) as order_cnt,
--     o.gmv,
--     round(o.gmv / nullif(o.order_cnt,0), 2) as avg_order_amount
-- from emp_base e
-- left join tool_agg t
--     on e.emp_code = t.emp_code
-- left join order_agg o
--     on e.emp_code = o.emp_code
-- ;

-- ============================================================
-- 示例 3：更复杂场景（≥7 张源表或 60+ 字段）— 分层建表
-- ============================================================
-- 中间表：tmp_{库名}.tmp_{需求简称}_{聚合主题}
-- 右表过滤条件推入子查询，LEFT JOIN → INNER JOIN
-- create table tmp_demo.tmp_order_daily_stat_city as
-- select
--     o.inc_day,
--     o.city,
--     c.city_name,
--     count(distinct o.order_id) as order_cnt,
--     sum(o.pay_amount) as gmv,
--     count(distinct o.customer_id) as customer_cnt,
--     coalesce(sum(case when o.order_type = 'scatter' then o.pay_amount end), 0) as scatter_gmv,
--     coalesce(sum(case when o.order_type = 'delivery' then o.pay_amount end), 0) as delivery_gmv
-- from dwd.dwd_order_detail_di o
-- inner join (
--     select
--         city_code,
--         city_name
--     from dwd.dim_city_info_df
--     where inc_day = '${bizdate}'
-- ) c on o.city = c.city_code
-- inner join (
--     select
--         customer_id
--     from dwd.dim_customer_info_df
--     where inc_day = '${bizdate}'
-- ) cu on o.customer_id = cu.customer_id
-- inner join (
--     select
--         product_id
--     from dwd.dim_product_info_df
--     where inc_day = '${bizdate}'
-- ) p on o.product_id = p.product_id
-- inner join (
--     select
--         shop_id
--     from dwd.dim_shop_info_df
--     where inc_day = '${bizdate}'
-- ) s on o.shop_id = s.shop_id
-- inner join (
--     select
--         category_id
--     from dwd.dim_category_info_df
--     where inc_day = '${bizdate}'
-- ) cat on o.category_id = cat.category_id
-- inner join (
--     select
--         payment_id
--     from dwd.dim_payment_info_df
--     where inc_day = '${bizdate}'
-- ) pay on o.payment_id = pay.payment_id
-- inner join (
--     select
--         logistics_id
--     from dwd.dim_logistics_info_df
--     where inc_day = '${bizdate}'
-- ) log on o.logistics_id = log.logistics_id
-- where o.inc_day = '${bizdate}'
--     and o.order_status >= '20'
-- group by
--     o.inc_day,
--     o.city,
--     c.city_name
-- ;
--
-- 最终表：从中间表取数
-- insert overwrite table ads_demo.ads_order_daily_stat_di partition (inc_day)
-- select
--     city,
--     city_name,
--     order_cnt,
--     customer_cnt,
--     gmv,
--     scatter_gmv,
--     delivery_gmv,
--     round(gmv / nullif(order_cnt,0), 2) as avg_order_amount,
--     round(gmv / nullif(customer_cnt,0), 2) as avg_customer_amount,
--     inc_day
-- from tmp_demo.tmp_order_daily_stat_city
-- where inc_day = '${bizdate}'
-- ;

-- ============================================================
-- 示例 4：宽表模式（条件≥3 个 / 需排查验收）— ★ 最常用
-- ============================================================
-- 三个强制原则：
--   1. 排查优先：判断中间字段（如 region_code、channel_type）必须暴露
--   2. 逻辑内聚：每个 is_sN 自包含，不依赖外层额外过滤
--   3. ADS 统一过滤：WHERE 只写 is_sN = 1
-- DWD+DWS 合并为一张宽表，减少中间表

-- DWS层：宽表（合并基础池 + 所有判断条件 + 判断中间字段）
-- drop table if exists tmp_demo.tmp_scenario_wide_$[time(yyyyMMdd,-60d)];
-- create table if not exists tmp_demo.tmp_scenario_wide_$[time(yyyyMMdd,-1d)] as
-- select
--     o.order_id,
--     o.customer_id,
--     o.region_code,
--     -- 判断中间字段（暴露供排查）
--     o.channel_type,
--     o.warehouse_id,
--     c.customer_level,
--     r.region_name,
--     -- 来源校验（derived 标记）
--     case when o.order_source = 'APP'
--               and o.order_type not in ('test','mock')
--               or o.order_source = 'API'
--               and o.order_type in ('standard','express')
--          then 1 else 0
--     end                                  as is_valid_source,
--     -- VIP 客户标记
--     case when c.customer_level in ('gold','platinum')
--          then '1' else '0'
--     end                                  as is_vip,
--     -- 场景标记（每个自包含）
--     case when o.total_amount > 10000
--          then 1 else 0
--     end                                  as is_s1,              -- 大额订单
--     case when coalesce(r.region_cnt, 0) = 1
--               and r.region_name is not null
--               and r.region_name <> o.region_code
--          then 1 else 0
--     end                                  as is_s2,              -- 区域异常
--     o.inc_day
-- from (
--     select
--         order_id,
--         customer_id,
--         region_code,
--         channel_type,
--         warehouse_id,
--         total_amount,
--         order_source,
--         order_type,
--         inc_day
--     from dw_demo.dwd_order_info_di
--     where inc_day = '$[time(yyyyMMdd,-1d)]'
--         and order_status >= '20'
-- ) o
-- inner join (                                                      -- 属性维度：过滤推入子查询
--     select
--         customer_id,
--         customer_level
--     from dw_demo.dim_customer_info_df
--     where inc_day = '$[time(yyyyMMdd,-1d)]'
--         and status = 'active'
-- ) c on o.customer_id = c.customer_id
-- left join dw_demo.dwd_product_info_df p on o.order_id = p.order_id  -- 条件字段：LEFT JOIN 保留全量
-- left join dw_demo.dwd_region_stat_di r    on o.region_code = r.region_code
--     -- ↑ region_stat 子查询用 CASE WHEN 合并多用途字段：
--     --   count(distinct region_id) as region_cnt,
--     --   case when count(distinct region_id)=1 then max(region_name) end as region_name
-- ;

-- ADS层：宽表过滤落表（直接用 is_sN，不额外 JOIN）
-- insert overwrite table ads_demo.ads_scenario_result_di partition (inc_day)
-- select
--     order_id,
--     customer_id,
--     region_code,
--     channel_type,                                                 -- 中间字段透传到 ADS 供排查
--     warehouse_id,
--     is_valid_source,
--     is_vip,
--     is_s1,
--     is_s2,
--     inc_day
-- from tmp_demo.tmp_scenario_wide_$[time(yyyyMMdd,-1d)]
-- where is_valid_source = 1                                       -- 条件1：来源校验
--     and is_vip = '1'                                            -- 条件2：VIP 客户
--     and (is_s1 = 1 or is_s2 = 1)                                -- 至少命中一个场景
-- ;

-- ============================================================
-- 编码规范速查
-- ============================================================
-- 1. 关键字小写：select, from, where, group by, left join
-- 2. 字段竖排：所有 select（含子查询/CTE/JOIN）字段均竖排，4 空格缩进，每字段独占一行
-- 3. WHERE 紧凑：≤3 个条件写一行，>3 个换行（and 前置 2 空格）
-- 4. 函数逗号无空格：coalesce(a,0), in('a','b')
-- 5. GROUP BY 灵活：≤3 字段紧凑，>3 字段竖排
-- 6. JOIN 与 ON 分行：left join table\n    on condition
-- 7. JOIN 键预处理：行级条件决定 JOIN 键时，先子查询计算再等值关联（禁止 ON 中写 CASE）
-- 8. 过滤条件下推：右表过滤条件推入子查询，LEFT JOIN → INNER JOIN（宽表模式除外）
-- 9. 简单场景用子查询：≤3 张源表用 from (select) alias
-- 10. 复杂场景用 CTE：4-6 张源表用 with ... as（逻辑清晰，但中间结果不落地）
-- 11. 更复杂场景分层建表：≥7 张源表或 60+ 字段按 DWD/DWS/ADS 分层（中间结果落盘，便于排查）
-- 12. 宽表模式（★ 最常用）：条件≥3 个 → DWD+DWS 合并宽表 + ADS WHERE
-- 13. 宽表三原则：① 排查优先（判断中间字段全暴露）② 逻辑内聚（is_sN 自包含）③ ADS 统一过滤
-- 14. 多层合并：DWD 无复杂聚合时合并到 DWS；同表多次读取合并为一次
-- 15. 架构决策树：先判断条件数量（≥3→宽表）再判断源表数量（≥7→分层），不要靠猜
-- 16. 同源表多用途合并：同一张表+相同 WHERE 读多次时，合并为一个子查询，用 CASE WHEN 条件聚合区分用途（如 region_cnt 计数 + single_region_id 单区域取值）
